config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/newaccount', to: 'users#new'
  get '/myaccount', to: 'users#show'
  get 'auth/:provider/callback',  to: 'sessions#create'
  get '/search', to: 'search#index'
  get '/help', to: 'help#index'
  get '/categories', to: 'categories#index'
  get '/editaccount', to: 'users#edit'
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  get 'checkout', to: 'checkout#new'
  get 'checkout_complete', to: 'checkout#create'
  resources :sessions, only: [:create, :destroy]

  resources :users, only: [:create, :edit, :update]
  resources :categories, only: [:index, :show]
  resources :books, only: [:index, :show]
  resources :charges, only: [:new, :create]

  namespace :account do
    get '/settings', to: 'settings#show'
    get '/membership', to: 'membership#show'
    get '/payment', to: 'payment#show'
    get '/checkout_history', to: 'checkout_history#index'
    get '/return', to: 'return#show'
  end

  get "/:slug" => "categories#show"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  belongs_to :publisher
  has_many :loans
  has_many :users, through: :loans
  validates_presence_of :title, :author, :description, :ISBN, :image_url
  validates :slug, uniqueness: true

  before_validation :generate_slug

  include PgSearch
  pg_search_scope :search_by_title, :against => :title

  def generate_slug
    self.slug = title.parameterize
  end

  def average_rating
    ReviewsWidget.fetch_average_rating(self.ISBN)
  end

  def self.recently_checked_out
    joins(:loans).order(created_at: :desc).limit(3)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params["id"])
    @review_widget = ReviewsWidget.fetch_reviews(@book.ISBN)
    @average_rating = ReviewsWidget.fetch_average_rating(@book.ISBN)
  end
end

app/views/books/show.html.erb
<div class="root">
  <p class="category"><%= link_to "Categories", categories_path %>  <i class="fa fa-angle-right arrow" aria-hidden="true"></i> <%= link_to @book.category.name, category_path(@book.category.slug) %></p>

  <div class="row">
    <div class=".col-sm- book">
      <%= image_tag(@book.image_url, class: "resize") %>
    </div>
    <div class=".col-sm- book">
      <h1 class="book"><%= @book.title  %></h1>
      <% if @book.subtitle.present? %>
        <h2 class="book"><%= @book.subtitle %></h2>
      <% end %>
      <p class="book"><b>By:</b> <%= @book.author %></p>
      <p class="book"><b>ISBN:</b> <%= @book.ISBN %></p>
      <p class="book"><b>Publisher:</b> <%= @book.publisher.name %></p>
      <p class="book"><span class="stars"><%= raw @average_rating %></span></p>
      <p class="book"><small><%= raw @average_rating %> avg. rating</small></p>
    </div>
    <div class="col-4 right">
      <% if current_user.nil? %>
        <a href="/signin"><button type="button" class="btn btn btn-lg btn-block">Free with 30-day trial</button></a>
        <p class="membership">Membership details <i class="fa fa-level-down" aria-hidden="true"></i></p>
        <ul class="membership">
          <li>A 30-day trial of ReBook services.</li>
          <li>Only one book can be checked out at a time. There is no limit to how many books can be checked out.</li>
          <li>Return books to ReBook at no additional cost with our shipping label.</li>
          <li>After your trial, ReBook is just $9.99/month.</li>
        </ul>
      <% elsif current_user.already_checked_out? == true %>
        <a href="/account/checkout_history"><button type="button" class="btn btn btn-lg btn-block">View Checkout History</button></a>

        <p class="membership">Membership details <i class="fa fa-level-down" aria-hidden="true"></i></p>
        <ul class="membership">
          <li>Members have access to ReBook's large collection of books.</li>
          <li>Only one book can be checked out at a time. There is no limit to how many books can be checked out a month.</li>
          <li>There is no "due date". ReBook members can check out a book as long as they want. No late fee applied.</li>
          <li>Return books to ReBook at no additional cost with our shipping label.</li>
        </ul>
      <% else %>
        <a href="/checkout?book=<%= @book.slug %>"><button type="button" class="btn btn btn-lg btn-block">Checkout</button></a>
        <p class="membership">Membership details <i class="fa fa-level-down" aria-hidden="true"></i></p>
        <ul class="membership">
          <li>Members have access to ReBook's large collection of books.</li>
          <li>Only one book can be checked out at a time. There is no limit to how many books can be checked out a month.</li>
          <li>There is no "due date". ReBook members can check out a book as long as they want. No late fee applied.</li>
          <li>Return books to ReBook at no additional cost with our shipping label.</li>
        </ul>
      <% end %>
    </div>
    
  <div class="row">
    <div class=".col-sm- book-show">
      <h3 class="description">Book Description:</h3>
      <p class="description"><%= @book.description %></p>
    </div>
  </div>
  <%= raw @review_widget %>
</div>
  <script>
    $(function() {
    $('span.stars').stars();
    });
  </script>