config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/newaccount', to: 'users#new'
  get '/myaccount', to: 'users#show'
  get 'auth/:provider/callback',  to: 'sessions#create'
  get '/search', to: 'search#index'
  get '/help', to: 'help#index'
  get '/categories', to: 'categories#index'
  get '/editaccount', to: 'users#edit'
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  get 'checkout', to: 'checkout#new'
  get 'checkout_complete', to: 'checkout#create'
  resources :sessions, only: [:create, :destroy]

  resources :users, only: [:create, :edit, :update]
  resources :categories, only: [:index, :show]
  resources :books, only: [:index, :show]
  resources :charges, only: [:new, :create]

  namespace :account do
    get '/settings', to: 'settings#show'
    get '/membership', to: 'membership#show'
    get '/payment', to: 'payment#show'
    get '/checkout_history', to: 'checkout_history#index'
    get '/return', to: 'return#show'
  end

  get "/:slug" => "categories#show"
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, uniqueness: true
  validates :slug, uniqueness: true

  has_many :books

  before_validation :generate_slug

  def generate_slug
    self.slug = name.parameterize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(:name)
  end

  def show
    @category = Category.find_by(slug: params["slug"] ||= params["id"])
    if @category.nil?
      @category = Category.find(params["id"])
    end
    @books = @category.books.order(:title)
  end
end

app/views/categories/index.html.erb
<div class="root">
  <h1 class="cat-index">View All Categories</h1>
  <div class="categories">
    <% @categories.each do |category| %>
      <p class="cat-index"><%= link_to category.name, category_path(category) %></p>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="root">
  <h2 class="category"><%= @category.name %></h3>
  <br>
  <br>
  <hr>

  <div class="row">
  <% @books.each do |book| %>
    <div class="col-sm- book">
      <%= link_to image_tag(book.image_url, class: "resize"), book_path(book) %>
      <p class="book-cat"><%= book.title %></p>
      <p class="book-cat">By <%= book.author %></p>
      <p><span class="stars"><%= book.average_rating %></span></p>
    </div>
  <% end %>
  </div>
</div>
<script>
  $(function() {
  $('span.stars').stars();
  });
</script>