config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/newaccount', to: 'users#new'
  get '/myaccount', to: 'users#show'
  get 'auth/:provider/callback',  to: 'sessions#create'
  get '/search', to: 'search#index'
  get '/help', to: 'help#index'
  get '/categories', to: 'categories#index'
  get '/editaccount', to: 'users#edit'
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  get 'checkout', to: 'checkout#new'
  get 'checkout_complete', to: 'checkout#create'
  resources :sessions, only: [:create, :destroy]

  resources :users, only: [:create, :edit, :update]
  resources :categories, only: [:index, :show]
  resources :books, only: [:index, :show]
  resources :charges, only: [:new, :create]

  namespace :account do
    get '/settings', to: 'settings#show'
    get '/membership', to: 'membership#show'
    get '/payment', to: 'payment#show'
    get '/checkout_history', to: 'checkout_history#index'
    get '/return', to: 'return#show'
  end

  get "/:slug" => "categories#show"
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
before_action :amount_to_be_charged
before_action :set_plan

  def new
  end

  def create
    if params[:subscription].include? 'yes'
      StripeTool.create_membership(email: params[:stripeEmail],
                                   stripe_token: params[:stripeToken],
                                   plan: @plan)
    else
      customer = StripeTool.create_customer(email: params[:stripeEmail],
                                            stripe_token: params[:stripeToken])
      charge = StripeTool.create_charge(customer_id: customer.id,
                                      amount: @amount,
                                      description: @description)
    end

    redirect_to myaccount_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def thanks
  end

  private

    def amount_to_be_charged
      @amount = 999
    end

    def set_plan
      @plan = 9999
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def pretty_amount(amount_in_cents)
    number_to_currency(amount_in_cents.to_f / 100)
  end
end

app/views/charges/new.html.erb
<div class="root">
  <div class="subscription">
    <h3 class="notice">You're close to entering a book lover's dream!</h3>
    <p class="notice">To take advantage of the benefits that come with the trial subscription, we'll need your billing information on record. If you enjoyed the free trial and would like to continue your subscription, the method of payment you've chosen will automatically be charged at the end of the trial period.</p>

  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>

    <%= hidden_field_tag :subscription, value: params[:subscription] %>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= @description %>"
            data-email="<%= current_user.email %>"
            data-bitcoin="true"
            data-locale="auto"></script>
  <% end %>
  </div>
</div>

app/views/charges/thanks.html.erb
<h2>Thanks, you paid <strong><%= pretty_amount(@amount) %></strong>!</h2>